// Automatically generated by flapigen
package org.iota.wallet;


public enum Api {
    GetTips(0),
    PostMessage(1),
    GetOutput(2);

    private final int value;
    Api(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Api fromInt(int x) {
        switch (x) {
            case 0: return GetTips;
            case 1: return PostMessage;
            case 2: return GetOutput;
            default: throw new Error("Invalid value for enum Api: " + x);
        }
    }
}
