[book]
authors = ["Sebastian Heusser <sebastian.heusser@iota.org>"]
language = "en"
multilingual = false
src = "./docs"
title = "IOTA Wallet Library"

[output.html]
default-theme = "iota"
theme = "./docs/theme"
git-repository-url = "https://github.com/iotaledger/wallet.rs"
git-repository-icon = "fa-github"
additional-css = ["./docs/theme/css/custom/header.css"]

[output.html.playpen]
editable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2