// Automatically generated by flapigen
package org.iota.wallet;


public enum AccountSignerType {
    Stronghold(0),
    LedgerNano(1),
    LedgerNanoSimulator(2);

    private final int value;
    AccountSignerType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static AccountSignerType fromInt(int x) {
        switch (x) {
            case 0: return Stronghold;
            case 1: return LedgerNano;
            case 2: return LedgerNanoSimulator;
            default: throw new Error("Invalid value for enum AccountSignerType: " + x);
        }
    }
}
