// Automatically generated by flapigen
package org.iota.wallet;


public enum AccountSignerType {
    STRONGHOLD(0),
    LEDGER_NANO(1),
    LEDGER_NANO_SIMULATOR(2);

    private final int value;
    AccountSignerType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static AccountSignerType fromInt(int x) {
        switch (x) {
            case 0: return STRONGHOLD;
            case 1: return LEDGER_NANO;
            case 2: return LEDGER_NANO_SIMULATOR;
            default: throw new Error("Invalid value for enum AccountSignerType: " + x);
        }
    }
}
