// Automatically generated by flapigen
package org.iota.wallet;


public final class AccountManager {

    public AccountManager(ManagerOptions options) {
        long a0 = options.mNativeObj;
        options.mNativeObj = 0;

        mNativeObj = init(a0);
        JNIReachabilityFence.reachabilityFence1(options);
    }
    private static native long init(long options);

    public final void stopBackgroundSync() {
        do_stopBackgroundSync(mNativeObj);
    }
    private static native void do_stopBackgroundSync(long self);

    public final void setStoragePassword(String password) {
        do_setStoragePassword(mNativeObj, password);
    }
    private static native void do_setStoragePassword(long self, String password);

    public final void setStrongholdPassword(String password) {
        do_setStrongholdPassword(mNativeObj, password);
    }
    private static native void do_setStrongholdPassword(long self, String password);

    public final void changeStrongholdPassword(String current_password, String new_password) {
        do_changeStrongholdPassword(mNativeObj, current_password, new_password);
    }
    private static native void do_changeStrongholdPassword(long self, String current_password, String new_password);

    public final String generateMnemonic() {
        String ret = do_generateMnemonic(mNativeObj);

        return ret;
    }
    private static native String do_generateMnemonic(long self);

    public final void storeMnemonic(AccountSignerType signer_type_enum, String mnemonic) {
        int a0 = signer_type_enum.getValue();
        do_storeMnemonic(mNativeObj, a0, mnemonic);

        JNIReachabilityFence.reachabilityFence1(signer_type_enum);
    }
    private static native void do_storeMnemonic(long self, int signer_type_enum, String mnemonic);

    public final void verifyMnemonic(String mnemonic) {
        do_verifyMnemonic(mNativeObj, mnemonic);
    }
    private static native void do_verifyMnemonic(long self, String mnemonic);

    public final AccountInitialiser createAccount(ClientOptions client_options) {
        long a0 = client_options.mNativeObj;
        client_options.mNativeObj = 0;

        long ret = do_createAccount(mNativeObj, a0);
        AccountInitialiser convRet = new AccountInitialiser(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(client_options);

        return convRet;
    }
    private static native long do_createAccount(long self, long client_options);

    public final void removeAccount(String account_id) {
        do_removeAccount(mNativeObj, account_id);
    }
    private static native void do_removeAccount(long self, String account_id);

    public final Account getAccount(String account_id) {
        long ret = do_getAccount(mNativeObj, account_id);
        Account convRet = new Account(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_getAccount(long self, String account_id);

    public final Account [] getAccounts() {
        Account [] ret = do_getAccounts(mNativeObj);

        return ret;
    }
    private static native Account [] do_getAccounts(long self);

    public final Message reattach(String account_id, MessageId message_id) {
        long a1 = message_id.mNativeObj;
        message_id.mNativeObj = 0;

        long ret = do_reattach(mNativeObj, account_id, a1);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(message_id);

        return convRet;
    }
    private static native long do_reattach(long self, String account_id, long message_id);

    public final Message promote(String account_id, MessageId message_id) {
        long a1 = message_id.mNativeObj;
        message_id.mNativeObj = 0;

        long ret = do_promote(mNativeObj, account_id, a1);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(message_id);

        return convRet;
    }
    private static native long do_promote(long self, String account_id, long message_id);

    public final Message retry(String account_id, MessageId message_id) {
        long a1 = message_id.mNativeObj;
        message_id.mNativeObj = 0;

        long ret = do_retry(mNativeObj, account_id, a1);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(message_id);

        return convRet;
    }
    private static native long do_retry(long self, String account_id, long message_id);

    public final Message internalTransfer(String from_account_id, String to_account_id, long amount) {
        long ret = do_internalTransfer(mNativeObj, from_account_id, to_account_id, amount);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_internalTransfer(long self, String from_account_id, String to_account_id, long amount);

    public final java.nio.file.Path backup(String destination) {
        String ret = do_backup(mNativeObj, destination);
        java.nio.file.Path convRet = java.nio.file.Paths.get(ret);

        return convRet;
    }
    private static native String do_backup(long self, String destination);

    public final void importAccounts(String source, String stronghold_password) {
        do_importAccounts(mNativeObj, source, stronghold_password);
    }
    private static native void do_importAccounts(long self, String source, String stronghold_password);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AccountManager(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}