// Automatically generated by flapigen
package org.iota.wallet;


public final class Account {

    private Account() {}

    public final Message transfer(Transfer transfer) {
        long a0 = transfer.mNativeObj;
        transfer.mNativeObj = 0;

        long ret = do_transfer(mNativeObj, a0);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(transfer);

        return convRet;
    }
    private static native long do_transfer(long self, long transfer);

    public final Address generateAddress() {
        long ret = do_generateAddress(mNativeObj);
        Address convRet = new Address(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_generateAddress(long self);

    public final Address getUnusedAddress() {
        long ret = do_getUnusedAddress(mNativeObj);
        Address convRet = new Address(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_getUnusedAddress(long self);

    public final boolean isLatestAddressUnused() {
        boolean ret = do_isLatestAddressUnused(mNativeObj);

        return ret;
    }
    private static native boolean do_isLatestAddressUnused(long self);

    public final Address latestAddress() {
        long ret = do_latestAddress(mNativeObj);
        Address convRet = new Address(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_latestAddress(long self);

    public final void setAlias(String alias) {
        do_setAlias(mNativeObj, alias);
    }
    private static native void do_setAlias(long self, String alias);

    public final void setClientOptions(ClientOptions options) {
        long a0 = options.mNativeObj;
        options.mNativeObj = 0;

        do_setClientOptions(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(options);
    }
    private static native void do_setClientOptions(long self, long options);

    public final Message [] listMessages(long count, long from, MessageType message_type) {
        int a2 = (message_type != null) ? message_type.getValue() : -1;

        Message [] ret = do_listMessages(mNativeObj, count, from, a2);

        JNIReachabilityFence.reachabilityFence1(message_type);

        return ret;
    }
    private static native Message [] do_listMessages(long self, long count, long from, int message_type);

    public final Address [] listSpentAddresses() {
        Address [] ret = do_listSpentAddresses(mNativeObj);

        return ret;
    }
    private static native Address [] do_listSpentAddresses(long self);

    public final Address [] listUnspentAddresses() {
        Address [] ret = do_listUnspentAddresses(mNativeObj);

        return ret;
    }
    private static native Address [] do_listUnspentAddresses(long self);

    public final java.util.Optional<Message> getMessage(MessageId message_id) {
        long a0 = message_id.mNativeObj;
        message_id.mNativeObj = 0;

        long ret = do_getMessage(mNativeObj, a0);
        java.util.Optional<Message> convRet;
        if (ret != 0) {
            convRet = java.util.Optional.of(new Message(InternalPointerMarker.RAW_PTR, ret));
        } else {
            convRet = java.util.Optional.empty();
        }

        JNIReachabilityFence.reachabilityFence1(message_id);

        return convRet;
    }
    private static native long do_getMessage(long self, long message_id);

    public final String alias() {
        String ret = do_alias(mNativeObj);

        return ret;
    }
    private static native String do_alias(long self);

    public final AccountBalance balance() {
        long ret = do_balance(mNativeObj);
        AccountBalance convRet = new AccountBalance(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_balance(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Account(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}