// Automatically generated by flapigen
package org.iota.wallet;


public final class AccountBalance {

    private AccountBalance() {}

    public final long getTotal() {
        long ret = do_getTotal(mNativeObj);

        return ret;
    }
    private static native long do_getTotal(long self);

    public final long getAvailable() {
        long ret = do_getAvailable(mNativeObj);

        return ret;
    }
    private static native long do_getAvailable(long self);

    public final long getIncoming() {
        long ret = do_getIncoming(mNativeObj);

        return ret;
    }
    private static native long do_getIncoming(long self);

    public final long getOutgoing() {
        long ret = do_getOutgoing(mNativeObj);

        return ret;
    }
    private static native long do_getOutgoing(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AccountBalance(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}