// Automatically generated by flapigen
package org.iota.wallet;


public interface AddressConsolidationNeededListener {


    void onAddressConsolidationNeeded(AddressConsolidationNeededEvent event);

}
