// Automatically generated by flapigen
package org.iota.wallet;


public enum Api {
    GET_TIPS(0),
    POST_MESSAGE(1),
    GET_OUTPUT(2);

    private final int value;
    Api(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Api fromInt(int x) {
        switch (x) {
            case 0: return GET_TIPS;
            case 1: return POST_MESSAGE;
            case 2: return GET_OUTPUT;
            default: throw new Error("Invalid value for enum Api: " + x);
        }
    }
}
