// Automatically generated by flapigen
package org.iota.wallet;


public final class BalanceChange {

    private BalanceChange() {}

    public final boolean is_spent() {
        boolean ret = do_is_spent(mNativeObj);

        return ret;
    }
    private static native boolean do_is_spent(long self);

    public final long spent() {
        long ret = do_spent(mNativeObj);

        return ret;
    }
    private static native long do_spent(long self);

    public final long received() {
        long ret = do_received(mNativeObj);

        return ret;
    }
    private static native long do_received(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BalanceChange(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}