// Automatically generated by flapigen
package org.iota.wallet;


public final class BalanceEvent {

    private BalanceEvent() {}

    public final String account_id() {
        String ret = do_account_id(mNativeObj);

        return ret;
    }
    private static native String do_account_id(long self);

    public final AddressWrapper address() {
        long ret = do_address(mNativeObj);
        AddressWrapper convRet = new AddressWrapper(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_address(long self);

    public final BalanceChange balance_change() {
        long ret = do_balance_change(mNativeObj);
        BalanceChange convRet = new BalanceChange(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_balance_change(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BalanceEvent(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}