// Automatically generated by flapigen
package org.iota.wallet;


public final class BrokerOptions {

    public BrokerOptions() {
        mNativeObj = init();
    }
    private static native long init();

    public final BrokerOptions automaticDisconnect(boolean disconnect) {
        long ret = do_automaticDisconnect(mNativeObj, disconnect);
        BrokerOptions convRet = new BrokerOptions(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_automaticDisconnect(long self, boolean disconnect);

    public final BrokerOptions timeout(long timeout) {
        long ret = do_timeout(mNativeObj, timeout);
        BrokerOptions convRet = new BrokerOptions(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_timeout(long self, long timeout);

    public final BrokerOptions useWebSockets(boolean use_ws) {
        long ret = do_useWebSockets(mNativeObj, use_ws);
        BrokerOptions convRet = new BrokerOptions(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_useWebSockets(long self, boolean use_ws);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ BrokerOptions(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}