// Automatically generated by flapigen
package org.iota.wallet;


public final class EventManager {

    private EventManager() {}

    public static EventId subscribe_errors(ErrorEvent cb) {
        long ret = do_subscribe_errors(cb);
        EventId convRet = new EventId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_subscribe_errors(ErrorEvent cb);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ EventManager(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}