// Automatically generated by flapigen
package org.iota.wallet;


public final class IndexationPayload {

    private IndexationPayload() {}

    public final int [] index() {
        int [] ret = do_index(mNativeObj);

        return ret;
    }
    private static native int [] do_index(long self);

    public final int [] data() {
        int [] ret = do_data(mNativeObj);

        return ret;
    }
    private static native int [] do_data(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ IndexationPayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}