// Automatically generated by flapigen
package org.iota.wallet;


public enum InputKind {
    UTXO(0),
    TREASURY(1);

    private final int value;
    InputKind(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static InputKind fromInt(int x) {
        switch (x) {
            case 0: return UTXO;
            case 1: return TREASURY;
            default: throw new Error("Invalid value for enum InputKind: " + x);
        }
    }
}
