// Automatically generated by flapigen
package org.iota.wallet;


public enum IotaAddress {
    Ed25519(0);

    private final int value;
    IotaAddress(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static IotaAddress fromInt(int x) {
        switch (x) {
            case 0: return Ed25519;
            default: throw new Error("Invalid value for enum IotaAddress: " + x);
        }
    }
}
