// Automatically generated by flapigen
package org.iota.wallet;


public enum ManagerStorage {
    STRONGHOLD(0),
    SQLITE(1);

    private final int value;
    ManagerStorage(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static ManagerStorage fromInt(int x) {
        switch (x) {
            case 0: return STRONGHOLD;
            case 1: return SQLITE;
            default: throw new Error("Invalid value for enum ManagerStorage: " + x);
        }
    }
}
