// Automatically generated by flapigen
package org.iota.wallet;


public final class ManagerOptions {

    public ManagerOptions() {
        mNativeObj = init();
    }
    private static native long init();

    public final void setStoragePath(String storage_path) {
        do_setStoragePath(mNativeObj, storage_path);
    }
    private static native void do_setStoragePath(long self, String storage_path);

    public final void setStorageType(ManagerStorage storage_type) {
        int a0 = storage_type.getValue();
        do_setStorageType(mNativeObj, a0);

        JNIReachabilityFence.reachabilityFence1(storage_type);
    }
    private static native void do_setStorageType(long self, int storage_type);

    public final void setStoragePassword(String storage_password) {
        do_setStoragePassword(mNativeObj, storage_password);
    }
    private static native void do_setStoragePassword(long self, String storage_password);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ManagerOptions(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}