// Automatically generated by flapigen
package org.iota.wallet;


public enum MessageType {
    RECEIVED(0),
    SENT(1),
    FAILED(2),
    UNCONFIRMED(3),
    VALUE(4);

    private final int value;
    MessageType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MessageType fromInt(int x) {
        switch (x) {
            case 0: return RECEIVED;
            case 1: return SENT;
            case 2: return FAILED;
            case 3: return UNCONFIRMED;
            case 4: return VALUE;
            default: throw new Error("Invalid value for enum MessageType: " + x);
        }
    }
}
