// Automatically generated by flapigen
package org.iota.wallet;


public final class MessageTransactionPayload {

    private MessageTransactionPayload() {}

    public final Essence essence() {
        long ret = do_essence(mNativeObj);
        Essence convRet = new Essence(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_essence(long self);

    public final UnlockBlock [] unlock_blocks() {
        UnlockBlock [] ret = do_unlock_blocks(mNativeObj);

        return ret;
    }
    private static native UnlockBlock [] do_unlock_blocks(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MessageTransactionPayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}