// Automatically generated by flapigen
package org.iota.wallet;


public final class MessageId {

    public static MessageId fromString(String str_rep) {
        long ret = do_fromString(str_rep);
        MessageId convRet = new MessageId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_fromString(String str_rep);

    public MessageId() {
        mNativeObj = init();
    }
    private static native long init();

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MessageId(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}