// Automatically generated by flapigen
package org.iota.wallet;


public enum MessageType {
    Received(0),
    Sent(1),
    Failed(2),
    Unconfirmed(3),
    Value(4);

    private final int value;
    MessageType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static MessageType fromInt(int x) {
        switch (x) {
            case 0: return Received;
            case 1: return Sent;
            case 2: return Failed;
            case 3: return Unconfirmed;
            case 4: return Value;
            default: throw new Error("Invalid value for enum MessageType: " + x);
        }
    }
}
