// Automatically generated by flapigen
package org.iota.wallet;


public final class MigratedFundsEntry {

    private MigratedFundsEntry() {}

    public final short [] tail_transaction_hash() {
        short [] ret = do_tail_transaction_hash(mNativeObj);

        return ret;
    }
    private static native short [] do_tail_transaction_hash(long self);

    public final SignatureLockedSingleOutput output() {
        long ret = do_output(mNativeObj);
        SignatureLockedSingleOutput convRet = new SignatureLockedSingleOutput(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_output(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MigratedFundsEntry(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}