// Automatically generated by flapigen
package org.iota.wallet;


public final class MilestonePayloadEssence {

    private MilestonePayloadEssence() {}

    public final long index() {
        long ret = do_index(mNativeObj);

        return ret;
    }
    private static native long do_index(long self);

    public final long timestamp() {
        long ret = do_timestamp(mNativeObj);

        return ret;
    }
    private static native long do_timestamp(long self);

    public final MessageId [] parents() {
        MessageId [] ret = do_parents(mNativeObj);

        return ret;
    }
    private static native MessageId [] do_parents(long self);

    public final short [] merkleProof() {
        short [] ret = do_merkleProof(mNativeObj);

        return ret;
    }
    private static native short [] do_merkleProof(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ MilestonePayloadEssence(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}