// Automatically generated by flapigen
package org.iota.wallet;


public enum OutputKind {
    SignatureLockedSingle(0),
    SignatureLockedDustAllowance(1),
    Treasury(2);

    private final int value;
    OutputKind(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static OutputKind fromInt(int x) {
        switch (x) {
            case 0: return SignatureLockedSingle;
            case 1: return SignatureLockedDustAllowance;
            case 2: return Treasury;
            default: throw new Error("Invalid value for enum OutputKind: " + x);
        }
    }
}
