// Automatically generated by flapigen
package org.iota.wallet;


public enum OutputKind {
    SIGNATURE_LOCKED_SINGLE(0),
    SIGNATURE_LOCKED_DUST_ALLOWANCE(1),
    TREASURY(2);

    private final int value;
    OutputKind(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static OutputKind fromInt(int x) {
        switch (x) {
            case 0: return SIGNATURE_LOCKED_SINGLE;
            case 1: return SIGNATURE_LOCKED_DUST_ALLOWANCE;
            case 2: return TREASURY;
            default: throw new Error("Invalid value for enum OutputKind: " + x);
        }
    }
}
