// Automatically generated by flapigen
package org.iota.wallet;


public final class ReceiptPayload {

    private ReceiptPayload() {}

    public final long index() {
        long ret = do_index(mNativeObj);

        return ret;
    }
    private static native long do_index(long self);

    public final boolean last() {
        boolean ret = do_last(mNativeObj);

        return ret;
    }
    private static native boolean do_last(long self);

    public final MigratedFundsEntry [] funds() {
        MigratedFundsEntry [] ret = do_funds(mNativeObj);

        return ret;
    }
    private static native MigratedFundsEntry [] do_funds(long self);

    public final long amount() {
        long ret = do_amount(mNativeObj);

        return ret;
    }
    private static native long do_amount(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ ReceiptPayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}