// Automatically generated by flapigen
package org.iota.wallet;


public enum RemainderValueStrategy {
    ReuseAddress(0),
    ChangeAddress(1);

    private final int value;
    RemainderValueStrategy(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static RemainderValueStrategy fromInt(int x) {
        switch (x) {
            case 0: return ReuseAddress;
            case 1: return ChangeAddress;
            default: throw new Error("Invalid value for enum RemainderValueStrategy: " + x);
        }
    }
}
