// Automatically generated by flapigen
package org.iota.wallet;


public enum RemainderValueStrategy {
    REUSE_ADDRESS(0),
    CHANGE_ADDRESS(1);

    private final int value;
    RemainderValueStrategy(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static RemainderValueStrategy fromInt(int x) {
        switch (x) {
            case 0: return REUSE_ADDRESS;
            case 1: return CHANGE_ADDRESS;
            default: throw new Error("Invalid value for enum RemainderValueStrategy: " + x);
        }
    }
}
