// Automatically generated by flapigen
package org.iota.wallet;


public final class RustHex {

    public static native String encode(String a0);

    public static native short [] decode(String s);

    private RustHex() {}
}