// Automatically generated by flapigen
package org.iota.wallet;


public final class StrongholdStatusEvent {

    private StrongholdStatusEvent() {}

    public final java.nio.file.Path snapshotPath() {
        String ret = do_snapshotPath(mNativeObj);
        java.nio.file.Path convRet = java.nio.file.Paths.get(ret);

        return convRet;
    }
    private static native String do_snapshotPath(long self);

    public final StrongholdStatusType status() {
        int ret = do_status(mNativeObj);
        StrongholdStatusType convRet = StrongholdStatusType.fromInt(ret);

        return convRet;
    }
    private static native int do_status(long self);

    public final java.time.Duration unlockedDuration() {
        float ret = do_unlockedDuration(mNativeObj);
        java.time.Duration convRet;
        java.time.Duration d = java.time.Duration.ofSeconds((int)ret);
        d.plusMillis((int)(ret % 1 * 1000));
        convRet = d;

        return convRet;
    }
    private static native float do_unlockedDuration(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ StrongholdStatusEvent(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}