// Automatically generated by flapigen
package org.iota.wallet;


public enum StrongholdStatusType {
    UNLOCKED(0),
    LOCKED(1);

    private final int value;
    StrongholdStatusType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static StrongholdStatusType fromInt(int x) {
        switch (x) {
            case 0: return UNLOCKED;
            case 1: return LOCKED;
            default: throw new Error("Invalid value for enum StrongholdStatusType: " + x);
        }
    }
}
