// Automatically generated by flapigen
package org.iota.wallet;


public enum TransferProgressType {
    SYNCING_ACCOUNT(0),
    SELECTING_INPUTS(1),
    GENERATING_REMAINDER_DEPOST_ADDRESS(2),
    SIGNING_TRANSACTION(3),
    PERFORMING_POW(4),
    BROADCASTING(5);

    private final int value;
    TransferProgressType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static TransferProgressType fromInt(int x) {
        switch (x) {
            case 0: return SYNCING_ACCOUNT;
            case 1: return SELECTING_INPUTS;
            case 2: return GENERATING_REMAINDER_DEPOST_ADDRESS;
            case 3: return SIGNING_TRANSACTION;
            case 4: return PERFORMING_POW;
            case 5: return BROADCASTING;
            default: throw new Error("Invalid value for enum TransferProgressType: " + x);
        }
    }
}
