// Automatically generated by flapigen
package org.iota.wallet;


public final class TransferProgressEvent {

    private TransferProgressEvent() {}

    public final String account_id() {
        String ret = do_account_id(mNativeObj);

        return ret;
    }
    private static native String do_account_id(long self);

    public final TransferProgressType event() {
        int ret = do_event(mNativeObj);
        TransferProgressType convRet = TransferProgressType.fromInt(ret);

        return convRet;
    }
    private static native int do_event(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TransferProgressEvent(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}