// Automatically generated by flapigen
package org.iota.wallet;


public final class Transfer {

    private Transfer() {}

    public static TransferBuilder builder(AddressWrapper address, long amount) {
        long a0 = address.mNativeObj;
        address.mNativeObj = 0;

        long ret = do_builder(a0, amount);
        TransferBuilder convRet = new TransferBuilder(InternalPointerMarker.RAW_PTR, ret);

        JNIReachabilityFence.reachabilityFence1(address);

        return convRet;
    }
    private static native long do_builder(long address, long amount);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Transfer(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}