// Automatically generated by flapigen
package org.iota.wallet;


public interface TransactionConfirmationChangeListener {


    void onConfirmationStateChange(TransactionConfirmationChangeEvent event);

}
