// Automatically generated by flapigen
package org.iota.wallet;


public final class TransactionConfirmationChangeEvent {

    private TransactionConfirmationChangeEvent() {}

    public final String account_id() {
        String ret = do_account_id(mNativeObj);

        return ret;
    }
    private static native String do_account_id(long self);

    public final Message message() {
        long ret = do_message(mNativeObj);
        Message convRet = new Message(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_message(long self);

    public final boolean confirmed() {
        boolean ret = do_confirmed(mNativeObj);

        return ret;
    }
    private static native boolean do_confirmed(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TransactionConfirmationChangeEvent(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}