// Automatically generated by flapigen
package org.iota.wallet;


public final class TreasuryTransactionPayload {

    private TreasuryTransactionPayload() {}

    public final MessageId input() {
        long ret = do_input(mNativeObj);
        MessageId convRet = new MessageId(InternalPointerMarker.RAW_PTR, ret);

        return convRet;
    }
    private static native long do_input(long self);

    public final long output() {
        long ret = do_output(mNativeObj);

        return ret;
    }
    private static native long do_output(long self);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ TreasuryTransactionPayload(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}