// Automatically generated by flapigen
package org.iota.wallet;


public enum UnlockBlockKind {
    ED25519(0),
    REFERENCE(1);

    private final int value;
    UnlockBlockKind(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static UnlockBlockKind fromInt(int x) {
        switch (x) {
            case 0: return ED25519;
            case 1: return REFERENCE;
            default: throw new Error("Invalid value for enum UnlockBlockKind: " + x);
        }
    }
}
