// Automatically generated by flapigen
package org.iota.wallet;


public enum ValueUnit {
    I(0),
    Ki(1),
    Mi(2),
    Gi(3),
    Ti(4),
    Pi(5);

    private final int value;
    ValueUnit(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static ValueUnit fromInt(int x) {
        switch (x) {
            case 0: return I;
            case 1: return Ki;
            case 2: return Mi;
            case 3: return Gi;
            case 4: return Ti;
            case 5: return Pi;
            default: throw new Error("Invalid value for enum ValueUnit: " + x);
        }
    }
}
